### PR TITLE
Fix unsubscribe from store on component unmount

### PR DESCRIPTION
**Pull request by nikcorg**
Closes https://github.com/musicglue/profile-components/issues/1190

### CODE REVIEW

**Comment by SomeHats** [comment]
can you `npm version patch` this?

Approved

[Approved with PullApprove](https://pullapprove.com/musicglue/relax-form/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=musicglue/relax-form)

**Comment by nikcorg** [comment]
Oh, of course. Do I need to `npm publish` as well?

**Comment by SomeHats** [comment]
once merged, yeah

**Comment by freesteph** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/musicglue/relax-form/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=musicglue/relax-form)

**Pull request merged**
